namespace Metacraft.VcsHardware;

public enum StarsSpecialKey
{
	NoOp,
	Beaconator,
	Cntr,
	Maps,
	Wx,
	Dcb,
	RngRing,
	Range,
	GreenBlank1,
	Core,
	SignOn,
	PrefSet,
	WhiteBlank1,
	Brite,
	Ldr,
	CharSize,
	Shift,
	GreenBlank2,
	GreenBlank3,
	Site,
	Mode,
	InitCntl,
	TrkRpos,
	TrkSusp,
	TermCntl,
	HndOff,
	FltData,
	MultiFunc,
	F8,
	F9,
	F10,
	Ca,
	F12,
	F13,
	F14,
	TgtGen,
	F16,
	Delta,
	Min,
	WhiteBlank2,
	WhiteBlank3
}

internal static class StarsSpecialKeyExtensions
{
	public static StarsSpecialKey ToStarsSpecialKey(this int buttonIndex)
	{
		return buttonIndex switch {
			0 => StarsSpecialKey.Beaconator,
			1 => StarsSpecialKey.Cntr,
			2 => StarsSpecialKey.Maps,
			3 => StarsSpecialKey.Wx,
			4 => StarsSpecialKey.Core,
			5 => StarsSpecialKey.SignOn,
			6 => StarsSpecialKey.Brite,
			7 => StarsSpecialKey.Ldr,
			8 => StarsSpecialKey.CharSize,
			9 => StarsSpecialKey.Shift,
			10 => StarsSpecialKey.Dcb,
			11 => StarsSpecialKey.RngRing,
			12 => StarsSpecialKey.Range,
			14 => StarsSpecialKey.PrefSet,
			15 => StarsSpecialKey.WhiteBlank1,
			16 => StarsSpecialKey.GreenBlank2,
			17 => StarsSpecialKey.GreenBlank3,
			18 => StarsSpecialKey.Site,
			19 => StarsSpecialKey.Mode,
			24 => StarsSpecialKey.InitCntl,
			25 => StarsSpecialKey.TrkRpos,
			26 => StarsSpecialKey.TrkSusp,
			27 => StarsSpecialKey.TermCntl,
			28 => StarsSpecialKey.HndOff,
			29 => StarsSpecialKey.FltData,
			30 => StarsSpecialKey.MultiFunc,
			31 => StarsSpecialKey.F8,
			32 => StarsSpecialKey.Delta,
			34 => StarsSpecialKey.F9,
			35 => StarsSpecialKey.F10,
			36 => StarsSpecialKey.Ca,
			37 => StarsSpecialKey.F12,
			38 => StarsSpecialKey.F13,
			39 => StarsSpecialKey.F14,
			40 => StarsSpecialKey.TgtGen,
			41 => StarsSpecialKey.F16,
			80 => StarsSpecialKey.Min,
			_ => StarsSpecialKey.NoOp
		};
	}
}
